# -*- coding: utf-8 -*-
"""mobilenet_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jbyuisR84_TJs-wjXfIo_pdqI6P7nFE
"""

!pip install roboflow pyyaml -q

from roboflow import Roboflow
rf = Roboflow(api_key="aWbrB4OYMvPn8LqQOOjr")
project = rf.workspace("s-workspace-dfaog").project("capstone-voerw")
version = project.version(1)
dataset = version.download("yolov8")

!pip install roboflow pyyaml -q

from roboflow import Roboflow
rf = Roboflow(api_key="aWbrB4OYMvPn8LqQOOjr")
project = rf.workspace("s-workspace-dfaog").project("capstone-voerw")
version = project.version(1)
dataset = version.download("yolov8")

from pathlib import Path
DATASET_DIR = Path(dataset.location)
print("DATASET_DIR:", DATASET_DIR)
print("존재 여부:", DATASET_DIR.exists())

# valid 폴더 이름 다를 수 있어서 둘 다 체크
valid_dir = DATASET_DIR / "valid"
if not valid_dir.exists():
    valid_dir = DATASET_DIR / "val"

def load_split(split_dir):
    images, labels = [], []
    img_dir = split_dir / "images"
    lbl_dir = split_dir / "labels"
    if not img_dir.exists():
        return images, labels
    for img_path in sorted(img_dir.glob("*")):
        if img_path.suffix.lower() not in {'.jpg', '.jpeg', '.png'}:
            continue
        lbl_path = lbl_dir / (img_path.stem + ".txt")
        if not lbl_path.exists():
            continue
        lines = lbl_path.read_text().strip().splitlines()
        if not lines:
            continue
        cls_idx = int(lines[0].split()[0])
        images.append(str(img_path))
        labels.append(cls_idx)
    return images, labels

train_images, train_labels = load_split(DATASET_DIR / "train")
val_images, val_labels = load_split(valid_dir)

# val이 비어있으면 train에서 20% 분리
if len(val_images) == 0:
    split = int(len(train_images) * 0.8)
    val_images, val_labels = train_images[split:], train_labels[split:]
    train_images, train_labels = train_images[:split], train_labels[:split]

print(f"Train: {len(train_images)}장, Val: {len(val_images)}장")

import tensorflow as tf
NUM_CLASSES = 12

IMG_SIZE = 224
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

def load_image(path, label):
    img = tf.io.read_file(path)
    img = tf.io.decode_image(img, channels=3, expand_animations=False)
    img.set_shape([None, None, 3])
    img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
    img = tf.cast(img, tf.float32) / 255.0
    return img, tf.one_hot(label, NUM_CLASSES)

def augment(img, label):
    img = tf.image.random_flip_left_right(img)
    img = tf.image.random_brightness(img, 0.2)
    img = tf.image.random_contrast(img, 0.8, 1.2)
    img = tf.image.random_saturation(img, 0.8, 1.2)
    img = tf.clip_by_value(img, 0.0, 1.0)
    return img, label

train_ds = (tf.data.Dataset.from_tensor_slices((train_images, train_labels))
            .shuffle(len(train_images))
            .map(load_image, num_parallel_calls=AUTOTUNE)
            .map(augment, num_parallel_calls=AUTOTUNE)
            .batch(BATCH_SIZE).prefetch(AUTOTUNE))

val_ds = (tf.data.Dataset.from_tensor_slices((val_images, val_labels))
          .map(load_image, num_parallel_calls=AUTOTUNE)
          .batch(BATCH_SIZE).prefetch(AUTOTUNE))

print("데이터셋 준비 완료")

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model

base = MobileNetV2(weights='imagenet', include_top=False, input_shape=(IMG_SIZE, IMG_SIZE, 3))
base.trainable = False

x = GlobalAveragePooling2D()(base.output)
x = BatchNormalization()(x)
x = Dropout(0.3)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.2)(x)
output = Dense(NUM_CLASSES, activation='softmax')(x)
model = Model(inputs=base.input, outputs=output)

callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True, monitor='val_accuracy'),
    tf.keras.callbacks.ReduceLROnPlateau(patience=3, factor=0.5, verbose=1),
]

model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss='categorical_crossentropy', metrics=['accuracy'])
print("=== Phase 1 ===")
model.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=callbacks)

base.trainable = True
for layer in base.layers[:-40]:
    layer.trainable = False

model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
              loss='categorical_crossentropy', metrics=['accuracy'])
print("=== Phase 2 ===")
model.fit(train_ds, validation_data=val_ds, epochs=20, callbacks=callbacks)

loss, acc = model.evaluate(val_ds)
print(f"최종 검증 정확도: {acc*100:.1f}%")

# class_names.txt 저장
class_names = ['bbq', 'coffee', 'curry', 'deri', 'go', 'ketchup', 'mayo', 'milk', 'mustard', 'oil', 'ori', 'soy']
with open('class_names.txt', 'w') as f:
    f.write('\n'.join(class_names))

# TFLite 변환
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
with open('stain_classifier_v3.tflite', 'wb') as f:
    f.write(tflite_model)

# 다운로드
from google.colab import files
files.download('stain_classifier_v3.tflite')
files.download('class_names.txt')

import numpy as np
from PIL import Image
import requests
from io import BytesIO

# TFLite 모델 로드
interpreter = tf.lite.Interpreter(model_path='stain_classifier_v3.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

class_names = ['bbq', 'coffee', 'curry', 'deri', 'go', 'ketchup', 'mayo', 'milk', 'mustard', 'oil', 'ori', 'soy']

def predict(img_path):
    img = Image.open(img_path).convert('RGB').resize((224, 224))
    x = np.array(img, dtype=np.float32) / 255.0
    x = np.expand_dims(x, axis=0)

    interpreter.set_tensor(input_details[0]['index'], x)
    interpreter.invoke()
    probs = interpreter.get_tensor(output_details[0]['index'])[0]

    top3_idx = probs.argsort()[::-1][:3]
    print("=== 예측 결과 ===")
    for i, idx in enumerate(top3_idx):
        print(f"  {i+1}위: {class_names[idx]:10s} {probs[idx]*100:.1f}%")

# 테스트 이미지 업로드
from google.colab import files
uploaded = files.upload()
for fname in uploaded:
    predict(fname)